<?php
 
$title = 'Authorization';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('authorization', array('action' => 'add')));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('login'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('pass'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();